<?php
/**
 * Admin view for the List Autoplugins page.
 * Uses the Plugin_List_Table class to display the list of plugins.
 *
 * @package WP-Autoplugin
 * @since 1.0.0
 * @version 1.0.5
 * @link https://wp-autoplugin.com
 * @license GPL-2.0+
 * @license https://www.gnu.org/licenses/gpl-2.0.html
 */

namespace WP_Autoplugin;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Initialize the WP_List_Table class.
$plugin_list_table = new Plugin_List_Table();
$plugin_list_table->prepare_items();
$autoplugins = $plugin_list_table->get_plugins();
$no_plugins  = empty( $autoplugins );

?>
<div class="wrap">
	<h1>
		<?php esc_html_e( 'Autoplugins', 'wp-autoplugin' ); ?>
		<a href="<?php echo esc_url( admin_url( 'admin.php?page=wp-autoplugin-generate' ) ); ?>" class="page-title-action"><?php esc_html_e( 'Generate New Plugin', 'wp-autoplugin' ); ?></a>
	</h1>
	<?php
	if ( $no_plugins ) {
		// Show a clear message if there are no plugins, along with a button to generate a new plugin.
		?>
		<div class="wp-autoplugin-card">
			<h2><?php esc_html_e( 'You don\'t have any autoplugins yet.', 'wp-autoplugin' ); ?></h2>
			<p><?php esc_html_e( 'Autoplugins are regular plugins, but they are generated by AI. You can manage them just like any other plugin. They will be listed here for your convenience.', 'wp-autoplugin' ); ?></p>
			<a href="<?php echo esc_url( admin_url( 'admin.php?page=wp-autoplugin-generate' ) ); ?>" class="button button-primary button-hero"><?php esc_html_e( 'Generate New Plugin', 'wp-autoplugin' ); ?></a>
		</div>
		<?php
	} else {
		$plugin_list_table->display();
	}
	?>
</div>
